const LINKEDIN_FEED_COMMENTS = [
    "Great perspective, thanks for sharing.",
    "This really made me think.",
    "Valuable insight.",
    "I completely agree with this.",
    "Well explained.",
    "Thanks for sharing your experience.",
    "This is an important reminder.",
    "I learned something new today.",
    "Great way to look at it.",
    "Very insightful post.",
    "I appreciate this perspective.",
    "Excellent breakdown.",
    "This deserves more attention.",
    "Such a practical idea.",
    "That's a strong point.",
    "Thanks for highlighting this.",
    "Really enjoyed reading this.",
    "This resonates with me.",
    "Great lesson here.",
    "Thought-provoking content.",
    "I like how you explained this.",
    "Practical advice.",
    "Thanks for putting this together.",
    "This is worth remembering.",
    "Great takeaway.",
    "That's a smart observation.",
    "Well said.",
    "I couldn't agree more.",
    "This is incredibly relevant.",
    "Interesting viewpoint.",
    "Great insights as always.",
    "Nicely written.",
    "This is very useful.",
    "Thanks for the valuable information.",
    "Appreciate you sharing this.",
    "A lot to think about here.",
    "Excellent perspective.",
    "This adds real value.",
    "Great reminder for everyone.",
    "I enjoyed this read.",
    "Very well articulated.",
    "This is something more people should discuss.",
    "That's a meaningful insight.",
    "Love this perspective.",
    "Great explanation.",
    "Thanks for sharing your thoughts.",
    "This is highly relevant today.",
    "Very inspiring.",
    "Excellent point.",
    "This is a helpful framework.",
    "I like this approach.",
    "Thanks for the inspiration.",
    "Great food for thought.",
    "This makes perfect sense.",
    "Really appreciate this insight.",
    "Well presented.",
    "Great analysis.",
    "This is a useful reminder.",
    "Strong message.",
    "I found this very helpful.",
    "Great content.",
    "Nicely summarized.",
    "Thanks for sharing these ideas.",
    "This is practical advice.",
    "Definitely worth considering.",
    "I like the way you framed this.",
    "Great example.",
    "This is spot on.",
    "Very informative.",
    "Thanks for this valuable post.",
    "Interesting analysis.",
    "This really stands out.",
    "Great point of view.",
    "Appreciate the clarity.",
    "This is something I'll remember.",
    "Thanks for sharing this lesson.",
    "Great insight into the topic.",
    "This is very relatable.",
    "I appreciate the practical examples.",
    "Well worth reading.",
    "Great perspective on this challenge.",
    "This adds a new angle.",
    "Really enjoyed your thoughts.",
    "Nice way to explain it.",
    "Great contribution.",
    "Thanks for sharing your knowledge.",
    "This is an eye-opener.",
    "Valuable lesson.",
    "This is worth discussing.",
    "Very meaningful.",
    "Great observations.",
    "Appreciate this thoughtful post.",
    "Well structured.",
    "Thanks for the perspective.",
    "This is an excellent reminder.",
    "Great discussion starter.",
    "Really appreciate this content.",
    "This is something I needed to read.",
    "Thanks for sharing this perspective.",
    "Great insights throughout.",
    "This encourages deeper thinking.",
    "Excellent reflection.",
    "That's a practical mindset.",
    "I appreciate the honesty.",
    "Very relevant in today's environment.",
    "This aligns with my experience.",
    "Great lesson for professionals.",
    "Well communicated.",
    "Thank you for sharing this.",
    "Insightful and actionable.",
    "This is a refreshing perspective.",
    "A valuable reminder.",
    "Great advice for anyone in the field.",
    "This is a conversation worth having.",
    "Thanks for sharing your viewpoint.",
    "Really strong message.",
    "Great balance between theory and practice.",
    "This is easy to relate to.",
    "I appreciate this thoughtful approach.",
    "Very well put.",
    "Great way to simplify a complex topic.",
    "This offers a lot of value.",
    "Interesting way to frame the issue.",
    "Thanks for encouraging discussion.",
    "Excellent learning opportunity.",
    "This sparked a new idea for me.",
    "Great perspective backed by experience.",
    "Thanks for the practical tips.",
    "This is insightful and timely.",
    "Appreciate the balanced viewpoint.",
    "Great reminder to stay focused.",
    "This highlights an important point.",
    "I enjoyed every part of this.",
    "Really useful insight.",
    "Great explanation with clear reasoning.",
    "This is a perspective worth sharing.",
    "I appreciate the examples you included.",
    "Nicely articulated.",
    "This gives a lot to reflect on.",
    "Very thoughtful.",
    "Great contribution to the conversation.",
    "This is genuinely helpful.",
    "Appreciate your expertise.",
    "Thanks for sharing your journey.",
    "This adds meaningful context.",
    "Excellent learning resource.",
    "Great perspective for anyone starting out.",
    "This is highly applicable.",
    "I found this especially interesting.",
    "Great reminder that small changes matter.",
    "This reflects real-world experience.",
    "Thank you for this thoughtful insight.",
    "Great perspective on continuous learning.",
    "This reinforces an important principle.",
    "Really appreciate the clarity of your message.",
    "Excellent insights with practical value.",
    "Thanks for bringing attention to this topic.",
    "This is a great example of thoughtful leadership.",
    "I appreciate the depth of this discussion.",
    "Great reminder to keep learning.",
    "This inspired me to think differently.",
    "Well worth reflecting on.",
    "Thanks for sharing this valuable perspective.",
    "This is something every professional can learn from.",
    "Great thoughts on the topic.",
    "Really appreciate this practical advice.",
    "This provides excellent context.",
    "Thanks for sharing these lessons.",
    "Great insight into today's challenges.",
    "This is very encouraging.",
    "I appreciate your thoughtful analysis.",
    "Excellent discussion.",
    "This perspective is refreshing.",
    "Great example of lifelong learning.",
    "Thanks for sharing your expertise with the community.",
    "This adds clarity to an important topic.",
    "I appreciate this balanced perspective.",
    "Very encouraging message.",
    "Great points throughout.",
    "This is a meaningful contribution.",
    "Thanks for sharing your experience and insights.",
    "Great reminder to stay curious.",
    "This is an insightful reflection.",
    "I appreciate the practical mindset.",
    "Excellent content as always.",
    "This is a helpful perspective for professionals.",
    "Great lesson to keep in mind.",
    "Thanks for encouraging thoughtful discussion.",
    "This highlights the importance of continuous improvement.",
    "Great perspective that many can benefit from.",
    "This is an excellent example of clear thinking.",
    "I appreciate the value you've shared here.",
    "Thanks for sharing such thoughtful insights.",
    "Great message with lasting value.",
    "This definitely adds to the conversation.",
    "I found this perspective inspiring.",
    "Great way to encourage meaningful discussion.",
    "This is a valuable contribution to the community.",
    "Thank you for sharing such practical insights.",
    "Looking forward to reading more of your thoughts."
];

const recentlyUsedComments = [];

function randomInt(min, max) {
    return min + Math.floor(Math.random() * (max - min + 1));
}

function selectRandomComment(options = {}) {
    const recentWindow = Math.max(0, Math.min(options.recentWindow || 20, 20));
    let availableComments = LINKEDIN_FEED_COMMENTS.filter(comment =>
        !recentlyUsedComments.includes(comment)
    );

    if (!availableComments.length) {
        resetRecentComments();
        availableComments = LINKEDIN_FEED_COMMENTS;
    }

    const lastComment = recentlyUsedComments[recentlyUsedComments.length - 1];
    const pool = availableComments.length > 1
        ? availableComments.filter(comment => comment !== lastComment)
        : availableComments;
    const comment = pool[randomInt(0, pool.length - 1)];

    recentlyUsedComments.push(comment);

    while (recentlyUsedComments.length > recentWindow) {
        recentlyUsedComments.shift();
    }

    return comment;
}

function resetRecentComments() {
    recentlyUsedComments.splice(0, recentlyUsedComments.length);
}

module.exports = {
    LINKEDIN_FEED_COMMENTS,
    recentlyUsedComments,
    resetRecentComments,
    selectRandomComment
};
